version: '1.0'

services:
    zoo1:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo1
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2.zookeeper:2888:3888 server.3=zoo3.zookeeper:2888:3888

    zoo2:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo2
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1.zookeeper:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3.zookeeper:2888:3888

    zoo3:
        image: 31z4/zookeeper
        restart: always
        hostname: zoo3
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1.zookeeper:2888:3888 server.2=zoo2.zookeeper:2888:3888 server.3=0.0.0.0:2888:3888